// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchzekwkfbU8-D640gflxo0v5Dl6mGTdo',
    appId: '1:900022792240:web:cf659e5c18ccb8179efdf5',
    messagingSenderId: '900022792240',
    projectId: 'summarize-it-afea9',
    authDomain: 'summarize-it-afea9.firebaseapp.com',
    storageBucket: 'summarize-it-afea9.appspot.com',
    measurementId: 'G-XDMV9TTE9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2owGYxbjLJb5daxiDO8tXm-20sdfO3NE',
    appId: '1:900022792240:android:cc98c39d1b5e8e399efdf5',
    messagingSenderId: '900022792240',
    projectId: 'summarize-it-afea9',
    storageBucket: 'summarize-it-afea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSs9KJsgmOZhJUqr9iQMGdlofd3k7sEc',
    appId: '1:900022792240:ios:50844214e4c644a69efdf5',
    messagingSenderId: '900022792240',
    projectId: 'summarize-it-afea9',
    storageBucket: 'summarize-it-afea9.appspot.com',
    iosBundleId: 'com.example.summarizeIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSs9KJsgmOZhJUqr9iQMGdlofd3k7sEc',
    appId: '1:900022792240:ios:8fb6d44501b94ccc9efdf5',
    messagingSenderId: '900022792240',
    projectId: 'summarize-it-afea9',
    storageBucket: 'summarize-it-afea9.appspot.com',
    iosBundleId: 'com.example.summarizeIt.RunnerTests',
  );
}
